global:
  imageOverrides:
    hypershift_deployment_controller: ""
    hypershift_addon_operator: ""
    apiserver_network_proxy: ""
    aws_encryption_provider: ""
    cluster_api: ""
    cluster_api_provider_agent: ""
    cluster_api_provider_aws: ""
    cluster_api_provider_azure: ""
    hypershift_operator: ""
    cluster_api_provider_kubevirt: ""
  namespace: default
  pullSecret: null
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
