apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: multicluster-switcher
spec:
  accessReviewResources:
    - group: operators.coreos.com
      resource: operatorgroups
      verb: list
    - group: packages.operators.coreos.com
      resource: packagemanifests
      verb: list
  description: 'With the multicluster switcher, you can easily switch between clusters'
  displayName: Get started with multicluster switcher
  conclusion: Congratulations! Multicluster switcher is ready to use.
  durationMinutes: 15
  icon: >-
    data:image/svg+xml;base64,PHN2ZyBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMDAgMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHdpZHRoPSIxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0ibTY2LjcgNTUuOGM2LjYgMCAxNi4xLTEuNCAxNi4xLTkuMiAwLS42IDAtMS4yLS4yLTEuOGwtMy45LTE3Yy0uOS0zLjctMS43LTUuNC04LjMtOC43LTUuMS0yLjYtMTYuMi02LjktMTkuNS02LjktMy4xIDAtNCA0LTcuNiA0LTMuNSAwLTYuMS0yLjktOS40LTIuOS0zLjIgMC01LjIgMi4xLTYuOCA2LjYgMCAwLTQuNCAxMi41LTUgMTQuMy0uMS4zLS4xLjctLjEgMSAuMSA0LjcgMTkuMiAyMC42IDQ0LjcgMjAuNm0xNy4xLTZjLjkgNC4zLjkgNC44LjkgNS4zIDAgNy40LTguMyAxMS40LTE5LjEgMTEuNC0yNC42IDAtNDYuMS0xNC40LTQ2LjEtMjMuOSAwLTEuMy4zLTIuNi44LTMuOS04LjkuNS0yMC4zIDIuMS0yMC4zIDEyLjIgMCAxNi41IDM5LjIgMzYuOSA3MC4yIDM2LjkgMjMuOCAwIDI5LjgtMTAuNyAyOS44LTE5LjIgMC02LjctNS44LTE0LjMtMTYuMi0xOC44IiBmaWxsPSIjZWQxYzI0Ii8+PHBhdGggZD0ibTgzLjggNDkuOGMuOSA0LjMuOSA0LjguOSA1LjMgMCA3LjQtOC4zIDExLjQtMTkuMSAxMS40LTI0LjYgMC00Ni4xLTE0LjQtNDYuMS0yMy45IDAtMS4zLjMtMi42LjgtMy45bDEuOS00LjhjLS4xLjMtLjEuNy0uMSAxIDAgNC44IDE5LjEgMjAuNyA0NC43IDIwLjcgNi42IDAgMTYuMS0xLjQgMTYuMS05LjIgMC0uNiAwLTEuMi0uMi0xLjh6IiBmaWxsPSIjMDEwMTAxIi8+PC9zdmc+
  introduction: 'With the multicluster switcher, you can easily switch between clusters.'
  tasks:
    - description: >


        To enable the console plug-in:

        1. From the Administrator [perspective]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }} of the OpenShift Container Platform web console, navigate to the cluster settings by clicking
        **[Administration]{{ "{{" }}highlight qs-nav-administration{{ "}}" }} > Cluster
        settings**.


        1. Click **Console (operator.openshift.io)** from the *Configuration* tab.


        1. On the *Console plugins* tab, check that the status of the `mce`
        plug-in is enabled.


        1. If you are also using Red Hat Advanced Cluster Management for Kubernetes, check that
        the status of the `acm` plug-in is also enabled.


        1. If the applicable plug-ins are disabled, complete the following steps for each plug-in:
          
          
          a. Click on the **Disabled** status. Select **Enable** from the dialog box and click on **Save**.  


        1. If you enabled any plug-ins, after a few moments, an alert with the text “Web console update is
        available” appears. Click the **Refresh web console** link to load the web
        console with the plug-ins enabled.
      review:
        failedTaskHelp: >-
          This task is incomplete. Try the task again.
        instructions: |-
          Verify that the console plug-in was enabled successfully:

            - In the navigation menu, is a cluster switcher present with the options **All clusters** and **local-cluster**? The cluster switcher should appear before the [perspective switcher]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }}.
      summary:
        failed: >-
          This task is incomplete. Try the task again, or read more about this
          topic.
        success: >-
          You just enabled the console plug-ins! Next, we'll enable the feature
          gate.
      title: Enable console plug-in
    - description: >

        **Warning**: This enables Technology Preview features 
          that are not part of the default features. Enabling this feature set 
          cannot be undone and prevents upgrades. **This feature set is NOT 
          recommended on production clusters**.

        To enable feature gate:

        1. From Administrator [perspective]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }} of the OpenShift Container Platform web console, navigate to the cluster settings by clicking **[Administration]{{ "{{" }}highlight qs-nav-administration{{ "}}" }} > Cluster settings**

        1. Click **FeatureGate** from the *Configuration* tab.

        1. On the *YAML* tab, edit the cluster instance to add the following specific feature sets:


            ```
            spec:
              featureSet: TechPreviewNoUpgrade
            ```

        1. Click **Save**.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |
          Verify that the feature gate was enabled successfully:

            - In the navigation menu, click **Administration > Cluster settings > 
            Configuration > FeatureGate > YAML**.

            - Do you see **TechPreviewNoUpgrade**?  
      summary:
        failed: >-
          Check your work to make sure that the Knative Service resource was
          created.
        success: You just created an instance of the Knative Service resource.
      title: Enable feature gate
    - description: >

        1. From the Administrator [perspective]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }}, navigate to *OperatorHub* by clicking
        **[Operators]{{ "{{" }}highlight qs-nav-operators{{ "}}" }}** from the navigation menu.

        1. Type “identity configuration management for Kubernetes” in the filter.

        1. Click the **identity configuration management for Kubernetes** tile to open the operator details. You may review the documentation by following the link provided.

        1. At the beginning of the **identity configuration management for Kubernetes**
        panel that opens, click **Install**.

        1. Fill out the *Install Operator* form then click **Install**. For more information on the options, see [Installing from the OperatorHub web console interface](https://identitatem.github.io/idp-mgmt-docs/install_connected.html#installing-from-the-operatorhub).


        1. On the *Installed Operators* page, wait for the status of *identity
        configuration management for Kubernetes* to change from
        *Installing* to *Succeeded*.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >
          Verify that **identity configuration management for Kubernetes** is
          installed:

            - In the **Status** column of the *Installed Operators* page, is the status of *identity 
            configuration management for Kubernetes** **Operator installed - Ready for use**?
      summary:
        failed: ...
        success: You just installed **identity configuration management for Kubernetes**
      title: Install **identity configuration management for Kubernetes**