apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: console-mce-monitor
  namespace: {{ .Values.global.namespace }}
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 60s
      port: http
      scheme: https
      scrapeTimeout: 10s
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
  jobLabel: console-mce-console
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
  selector:
    matchLabels:
      app: console-mce
