# Copyright Contributors to the Open Cluster Management project
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: mce
spec:
  displayName: Red Hat MultiCluster Engine
  backend:
    service:
      basePath: /plugin/
      name: console-mce-console
      namespace: {{ .Values.global.namespace }}
      port: 3000
  i18n:
    loadType: Preload
  proxy:
    - alias: console
      authorization: UserToken
      endpoint:
        service:
          name: console-mce-console
          namespace: {{ .Values.global.namespace }}
          port: 3000
        type: Service
