apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: multicluster-switcher
spec:
  accessReviewResources:
    - group: operators.coreos.com
      resource: operatorgroups
      verb: list
    - group: packages.operators.coreos.com
      resource: packagemanifests
      verb: list
  description: 'With the multicluster switcher, you can work with your managed clusters from a single console and change between them quickly'
  displayName: Get started with the multicluster switcher
  conclusion: Congratulations! Multicluster switcher is ready to use.
  durationMinutes: 5
  icon: >-
    data:image/svg+xml;base64,PHN2ZyBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMDAgMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHdpZHRoPSIxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0ibTY2LjcgNTUuOGM2LjYgMCAxNi4xLTEuNCAxNi4xLTkuMiAwLS42IDAtMS4yLS4yLTEuOGwtMy45LTE3Yy0uOS0zLjctMS43LTUuNC04LjMtOC43LTUuMS0yLjYtMTYuMi02LjktMTkuNS02LjktMy4xIDAtNCA0LTcuNiA0LTMuNSAwLTYuMS0yLjktOS40LTIuOS0zLjIgMC01LjIgMi4xLTYuOCA2LjYgMCAwLTQuNCAxMi41LTUgMTQuMy0uMS4zLS4xLjctLjEgMSAuMSA0LjcgMTkuMiAyMC42IDQ0LjcgMjAuNm0xNy4xLTZjLjkgNC4zLjkgNC44LjkgNS4zIDAgNy40LTguMyAxMS40LTE5LjEgMTEuNC0yNC42IDAtNDYuMS0xNC40LTQ2LjEtMjMuOSAwLTEuMy4zLTIuNi44LTMuOS04LjkuNS0yMC4zIDIuMS0yMC4zIDEyLjIgMCAxNi41IDM5LjIgMzYuOSA3MC4yIDM2LjkgMjMuOCAwIDI5LjgtMTAuNyAyOS44LTE5LjIgMC02LjctNS44LTE0LjMtMTYuMi0xOC44IiBmaWxsPSIjZWQxYzI0Ii8+PHBhdGggZD0ibTgzLjggNDkuOGMuOSA0LjMuOSA0LjguOSA1LjMgMCA3LjQtOC4zIDExLjQtMTkuMSAxMS40LTI0LjYgMC00Ni4xLTE0LjQtNDYuMS0yMy45IDAtMS4zLjMtMi42LjgtMy45bDEuOS00LjhjLS4xLjMtLjEuNy0uMSAxIDAgNC44IDE5LjEgMjAuNyA0NC43IDIwLjcgNi42IDAgMTYuMS0xLjQgMTYuMS05LjIgMC0uNiAwLTEuMi0uMi0xLjh6IiBmaWxsPSIjMDEwMTAxIi8+PC9zdmc+
  introduction: 'With the multicluster switcher, you can work with your managed clusters from a single console and change between them quickly.'
  tasks:
    - title: Enable console plug-in
      description: |-
        1. From the Administrator [perspective]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }} of the OpenShift Container Platform web console, navigate to the cluster settings by clicking
        **[Administration]{{ "{{" }}highlight qs-nav-administration{{ "}}" }} > Cluster
        settings**.

        1. Click **Console (operator.openshift.io)** from the *Configuration* tab.

        1. On the *Console plugins* tab, check that the status of the `mce`
        plug-in is enabled.

        1. If you are also using Red Hat Advanced Cluster Management for Kubernetes, check that
        the status of the `acm` plug-in is also enabled.

        1. If the applicable plug-ins are disabled, complete the following steps for each plug-in:
          
            1. Click on the **Disabled** status.
         
            1. Select **Enable** from the dialog box.
         
            1. Click on **Save**.  

        1. If you enabled any plug-ins, after a few moments, an alert with the text “Web console update is
        available” appears. Click the **Refresh web console** link to load the web
        console with the plug-ins enabled.
      review:
        failedTaskHelp: This task is incomplete. Try the task again.
        instructions: |-
          Verify that the console plug-in is enabled:

            - In the navigation menu, is a cluster switcher present with the options **All Clusters** and **local-cluster**? The cluster switcher should appear before the [perspective switcher]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }}.
    - title: Understand feature gates  
      description: |-
        The remaining steps require you to use feature gates to activate the `TechPreviewNoUpgrade` feature set.

        **Warning**: Using the `TechPreviewNoUpgrade` feature set enables Technology Preview features 
            that are not part of the default features. Enabling this feature set 
            cannot be undone and prevents upgrades. **This feature set is NOT 
            recommended on production clusters**.

        For more information, see [Enabling OpenShift Container Platform features using FeatureGates](https://docs.openshift.com/container-platform/4.10/nodes/clusters/nodes-cluster-enabling-features.html).
      review:
        instructions: |
          Do you acknowledge that enabling the feature gate is irreversible and not recommended for production clusters?
        failedTaskHelp: Do not proceed with the remaining steps.
    - title: Enable feature gate 
      description: |-
        1. From Administrator [perspective]{{ "{{" }}highlight qs-perspective-switcher{{ "}}" }} of the OpenShift Container Platform web console, navigate to the cluster settings by clicking **[Administration]{{ "{{" }}highlight qs-nav-administration{{ "}}" }} > Cluster settings**

        1. Click **FeatureGate** from the *Configuration* tab.

        1. On the *YAML* tab, edit the cluster instance to add the following specific feature sets:

            ```
            spec:
              featureSet: TechPreviewNoUpgrade
            ```

        1. Click **Save**.
      review:
        failedTaskHelp: This task is incomplete. Try the task again.
        instructions: |
          Verify that the feature gate is enabled:

            - In the navigation menu, click **Administration > Cluster settings**. Do you see a warning stating that the cluster cannot be updated because of the `TechPreviewNoUpgrade` feature set?
            - If you have any managed clusters that were previously imported or created, do they appear in the cluster switcher after a few minutes?
    
