apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-metrics-service
  namespace: '{{ default "capa-system" .Values.global.namespace }}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    cluster.x-k8s.io/provider: infrastructure-aws
  type: ClusterIP
