apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.amazonaws.com/role: ''
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: controller-manager
  name: capa-controller-manager
