# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

global:
  imageOverrides: {}
  templateOverrides: {}
  namespace: default
  pullSecret: null
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
  ocpVersion: 4.12.0
org: open-cluster-management
