apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "backplane.open-cluster-management.io/v1alpha1",
          "kind": "BackplaneConfig",
          "metadata": {
            "name": "backplaneconfig-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.10.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: backplane-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: BackplaneConfig is the Schema for the backplaneconfigs API
      displayName: Backplane Config
      kind: BackplaneConfig
      name: backplaneconfigs.backplane.open-cluster-management.io
      version: v1alpha1
  description: Provides the components making up the backplane
  displayName: Backplane Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - namespaces
          - secrets
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - apiextensions.k8s.io
          - apps
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          - customresourcedefinitions
          - deployments
          - serviceaccounts
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - update
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - apiservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - backplane.open-cluster-management.io
          resources:
          - backplaneconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - backplane.open-cluster-management.io
          resources:
          - backplaneconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - backplane.open-cluster-management.io
          resources:
          - backplaneconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - hive.openshift.io
          resources:
          - hiveconfigs
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - operator.open-cluster-management.io
          resources:
          - clustermanagers
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - operator.open-cluster-management.io
          resources:
          - clustermanagers/status
          verbs:
          - patch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - bind
          - create
          - delete
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: backplane-operator
      deployments:
      - name: backplane-operator
        spec:
          replicas: 2
          selector:
            matchLabels:
              control-plane: backplane-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: backplane-operator
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /app/backplane-operator
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/open-cluster-management/backplane-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: backplane-operator
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 2Gi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: backplane-operator
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: backplane-operator-webhook
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: backplane-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - backplane
  links:
  - name: Backplane Operator
    url: https://backplane-operator.domain
  maintainers:
  - email: acm-contact@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
