apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "multicluster.openshift.io/v1",
          "kind": "MultiClusterEngine",
          "metadata": {
            "name": "multiclusterengine-sample"
          },
          "spec": {}
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.16.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: multicluster-engine.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterEngine is the Schema for the multiclusterengines API
      displayName: MultiCluster Engine
      kind: MultiClusterEngine
      name: multiclusterengines.multicluster.openshift.io
      specDescriptors:
      - description: 'Specifies deployment replication for improved availability.
          Options are: Basic and High (default)'
        displayName: Availability Configuration
        path: availabilityConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:select:High
        - urn:alm:descriptor:com.tectonic.ui:select:Basic
      - description: Provides optional configuration for components
        displayName: Component Configuration
        path: components
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Override pull secret for accessing MultiClusterEngine operand
          and endpoint images
        displayName: Image Pull Secret
        path: imagePullSecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Developer Overrides
        displayName: Developer Overrides
        path: overrides
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Location where MCE resources will be placed
        displayName: Target Namespace
        path: targetNamespace
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1
  description: Provides the components making up the multiclusterengine
  displayName: MultiCluster Engine
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - configmaps/status
          - namespaces
          - secrets
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - endpoints
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - apiextensions.k8s.io
          - apps
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          - customresourcedefinitions
          - deployments
          - serviceaccounts
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - ""
          - batch
          - tower.ansible.com
          resources:
          - ansiblejobs
          - clusterdeployments
          - jobs
          - machinepools
          - serviceaccounts
          verbs:
          - get
        - apiGroups:
          - ""
          - batch
          - tower.ansible.com
          resources:
          - ansiblejobs
          - jobs
          - secrets
          - serviceaccounts
          verbs:
          - create
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - update
        - apiGroups:
          - action.open-cluster-management.io
          resources:
          - managedclusteractions
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - clustermanagementaddons
          - clustermanagementaddons/finalizers
          - managedclusteraddons
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - agent.open-cluster-management.io
          - cluster.open-cluster-management.io
          - inventory.open-cluster-management.io
          - operator.open-cluster-management.io
          resources:
          - baremetalassets
          - klusterletaddonconfigs
          - managedclusters
          - multiclusterhubs
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - apiservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          - config.openshift.io
          resources:
          - clusterversions
          - tokenreviews
          verbs:
          - create
          - get
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - clustercurators
          - clustercurators/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - managedclustersets/join
          verbs:
          - create
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - discovery.open-cluster-management.io
          resources:
          - discoveredclusters
          - discoveryconfigs
          verbs:
          - approve
          - bind
          - create
          - delete
          - deletecollection
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - discovery.open-cluster-management.io
          resources:
          - discoveryconfigs
          verbs:
          - get
          - list
        - apiGroups:
          - hive.openshift.io
          resources:
          - clusterclaims
          - clusterdeployments
          - clusterpools
          - machinepools
          verbs:
          - approve
          - bind
          - create
          - delete
          - deletecollection
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hive.openshift.io
          resources:
          - hiveconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - imageregistry.open-cluster-management.io
          resources:
          - managedclusterimageregistries
          - managedclusterimageregistries/status
          verbs:
          - approve
          - bind
          - create
          - delete
          - deletecollection
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - internal.open-cluster-management.io
          resources:
          - managedclusterinfos
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - migration.k8s.io
          resources:
          - storageversionmigrations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - multicluster.openshift.io
          resources:
          - multiclusterengines
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - multicluster.openshift.io
          resources:
          - multiclusterengines/finalizers
          verbs:
          - update
        - apiGroups:
          - multicluster.openshift.io
          resources:
          - multiclusterengines/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operator.open-cluster-management.io
          resources:
          - clustermanagers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.open-cluster-management.io
          resources:
          - clustermanagers/status
          verbs:
          - patch
          - update
        - apiGroups:
          - operator.openshift.io
          resources:
          - consoles
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - bind
          - create
          - delete
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - register.open-cluster-management.io
          resources:
          - managedclusters/accept
          verbs:
          - update
        serviceAccountName: multicluster-engine-operator
      deployments:
      - name: multicluster-engine-operator
        spec:
          replicas: 2
          selector:
            matchLabels:
              control-plane: backplane-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: backplane-operator
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /app/backplane-operator
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/stolostron/backplane-operator:latest
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: backplane-operator
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 2Gi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: multicluster-engine-operator
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: multicluster-engine-operator-webhook
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: multicluster-engine-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - multiclusterengine
  links:
  - name: Multicluster Engine
    url: https://multicluster-engine.domain
  maintainers:
  - email: acm-contact@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
    url: https://multicluster-engine.domain
  version: 0.0.1
