apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: '{{ .Values.global.namespace }}'
  name: images
spec:
  port:
    targetPort: config-server
  to:
    kind: Service
    name: image-based-install-config
    weight: 100
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt