apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-inject-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  - clusterpools
  - clusterclaims
  - machinepools
  verbs:
  - get
  - list
  - watch
