
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: multicluster-engine-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  - namespaces
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - apiextensions.k8s.io
  - apps
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - customresourcedefinitions
  - deployments
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  - batch
  - tower.ansible.com
  resources:
  - ansiblejobs
  - clusterdeployments
  - jobs
  - machinepools
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ""
  - batch
  - tower.ansible.com
  resources:
  - ansiblejobs
  - jobs
  - secrets
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - action.open-cluster-management.io
  resources:
  - managedclusteractions
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.open-cluster-management.io
  - cluster.open-cluster-management.io
  - inventory.open-cluster-management.io
  - operator.open-cluster-management.io
  resources:
  - baremetalassets
  - klusterletaddonconfigs
  - managedclusters
  - multiclusterhubs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  - config.openshift.io
  resources:
  - clusterversions
  - tokenreviews
  verbs:
  - create
  - get
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clustercurators
  - clustercurators/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets/join
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters
  - discoveryconfigs
  verbs:
  - approve
  - bind
  - create
  - delete
  - deletecollection
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs
  verbs:
  - get
  - list
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterclaims
  - clusterdeployments
  - clusterpools
  - machinepools
  verbs:
  - approve
  - bind
  - create
  - delete
  - deletecollection
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - hiveconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - imageregistry.open-cluster-management.io
  resources:
  - managedclusterimageregistries
  - managedclusterimageregistries/status
  verbs:
  - approve
  - bind
  - create
  - delete
  - deletecollection
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - internal.open-cluster-management.io
  resources:
  - managedclusterinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migration.k8s.io
  resources:
  - storageversionmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.openshift.io
  resources:
  - multiclusterengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.openshift.io
  resources:
  - multiclusterengines/finalizers
  verbs:
  - update
- apiGroups:
  - multicluster.openshift.io
  resources:
  - multiclusterengines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - clustermanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - clustermanagers/status
  verbs:
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - managedclusters/accept
  verbs:
  - update
