{{- if .Values.global.deployOnOCP }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.proxy.open-cluster-management.io
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
spec:
  service:
    namespace: {{ .Values.global.namespace }}
    name: ocm-proxyserver
  group: proxy.open-cluster-management.io
  version: v1beta1
  groupPriorityMinimum: 10000
  versionPriority: 20
{{- end }}
