# Copyright Contributors to the Open Cluster Management project

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app: ocm-webhook
  name: ocm-validating-webhook
webhooks:
  - name: ocm.validating.webhook.admission.open-cluster-management.io
    admissionReviewVersions:
      - v1
    clientConfig:
      {{- if not .Values.global.deployOnOCP }}
      caBundle: {{ .Values.global.servingCertCABundle }}
      {{- end }}
      service:
        name: ocm-webhook
        namespace: {{ .Values.global.namespace }}
        path: /validating
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - hive.openshift.io
        operations:
          - CREATE
          - UPDATE
        apiVersions:
          - "v1"
        resources:
          - clusterpools
        scope: '*'
      - apiGroups:
          - hive.openshift.io
        operations:
          - CREATE
          - UPDATE
          - DELETE
        apiVersions:
          - "v1"
        resources:
          - clusterdeployments
        scope: '*'
      - apiGroups:
          - cluster.open-cluster-management.io
        operations:
          - CREATE
          - UPDATE
        apiVersions:
          - "*"
        resources:
          - managedclustersets
      - apiGroups:
          - cluster.open-cluster-management.io
        operations:
          - CREATE
          - UPDATE
          - DELETE
        apiVersions:
          - "*"
        resources:
          - managedclusters
    sideEffects: None
    timeoutSeconds: 10
