apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
  name: managed-serviceaccount
spec:
  addOnMeta:
    description: managed-serviceaccount
    displayName: managed-serviceaccount
  supportedConfigs:
  - defaultConfig:
      name: managed-serviceaccount-addon-deploy-config
      namespace: '{{ .Values.global.namespace }}'
    group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
  - defaultConfig:
      name: managed-serviceaccount-2.5
    group: addon.open-cluster-management.io
    resource: addontemplates
