apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:managed-serviceaccount'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Values.org }}:{{ .Chart.Name }}:managed-serviceaccount'
subjects:
- kind: ServiceAccount
  name: managed-serviceaccount
  namespace: '{{ .Values.global.namespace }}'
