
# Source: managed-serviceaccount/templates/clustermanagementaddon.yaml
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: managed-serviceaccount
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    displayName: managed-serviceaccount
    description: managed-serviceaccount
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
# TODO: uncomment when the agentInstallNamespace field is added to the ocm repo
    # defaultConfig:
    #   namespace: default
    #   name: managed-serviceaccount-addon-deploy-config
  - group: addon.open-cluster-management.io
    resource: addontemplates
    defaultConfig:
      name: managed-serviceaccount-2.4