apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "backplaneconfig.open-cluster-management.io"
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: backplane-operator-webhook-service
      namespace: system
      path: /validate-backplane-open-cluster-management-io-v1alpha1-backplaneconfig
  failurePolicy: Fail
  name: backplaneconfig.open-cluster-management.io
  rules:
  - apiGroups:
    - backplane.open-cluster-management.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backplaneconfigs
  sideEffects: None
