apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "multiclusterengines.multicluster.openshift.io"
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: multicluster-engine-operator-webhook-service
      namespace: system
      path: /validate-multicluster-openshift-io-v1-multiclusterengine
  failurePolicy: Fail
  name: multiclusterengines.multicluster.openshift.io
  rules:
  - apiGroups:
    - multicluster.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - multiclusterengines
  sideEffects: None
