apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-operator
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      control-plane: hive-operator
      controller-tools.k8s.io: '1.0'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: hive-operator
        controller-tools.k8s.io: '1.0'
        ocm-antiaffinity-selector: hive-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - hive-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - hive-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - command:
        - /opt/services/hive-operator
        - --log-level
        - info
        env:
        - name: CLI_CACHE_DIR
          value: /var/cache/kubectl
        - name: HIVE_OPERATOR_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TMPDIR
          value: /tmp
        image: '{{ .Values.global.imageOverrides.openshift_hive }}'
        imagePullPolicy: '{{ .Values.global.pullPolicy }}'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        name: hive-operator
        ports:
        - containerPort: 2112
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/cache/kubectl
          name: kubectl-cache
        - mountPath: /tmp
          name: tmp
      hostIPC: false
      hostNetwork: false
      hostPID: false
      imagePullSecrets: ''
      nodeSelector: ''
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: hive-operator
      terminationGracePeriodSeconds: 10
      tolerations: ''
      volumes:
      - emptyDir: {}
        name: kubectl-cache
      - emptyDir: {}
        name: tmp
