# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:backplane:foundation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:backplane:foundation
subjects:
  - kind: ServiceAccount
    name: ocm-foundation-sa
    namespace: {{ .Values.global.namespace }}