apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-foundation-inject-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterdeployments", "clusterpools", "clusterclaims", "machinepools"]
    verbs: ["*"]
