# Copyright Contributors to the Open Cluster Management project

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clusterlifecycle-state-metrics-v2
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 60s
    port: https
    scheme: https
    scrapeTimeout: 10s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: clc-app
  selector:
    matchLabels:
      clc-app: clusterlifecycle-state-metrics-v2
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}