apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: backplane-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterEngine is the Schema for the multiclusterengines API
      displayName: Multi Cluster Engine
      kind: MultiClusterEngine
      name: multiclusterengines.multicluster.openshift.io
      version: v1alpha1
  description: Provides the components making up the backplane
  displayName: Backplane Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - backplane
  links:
  - name: Backplane Operator
    url: https://backplane-operator.domain
  maintainers:
  - email: acm-contact@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
