apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: multicluster-engine.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterEngine is the Schema for the multiclusterengines API
      displayName: MultiCluster Engine
      kind: MultiClusterEngine
      name: multiclusterengines.multicluster.openshift.io
      specDescriptors:
      - description: 'Specifies deployment replication for improved availability.
          Options are: Basic and High (default)'
        displayName: Availability Configuration
        path: availabilityConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:select:High
        - urn:alm:descriptor:com.tectonic.ui:select:Basic
      - description: Override pull secret for accessing MultiClusterEngine operand
          and endpoint images
        displayName: Image Pull Secret
        path: imagePullSecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Location where MCE resources will be placed
        displayName: Target Namespace
        path: targetNamespace
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      version: v1alpha1
  description: Provides the components making up the multiclusterengine
  displayName: MultiCluster Engine
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - multiclusterengine
  links:
  - name: Multicluster Engine
    url: https://multicluster-engine.domain
  maintainers:
  - email: acm-contact@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
    url: https://multicluster-engine.domain
  version: 0.0.0
