# Copyright Contributors to the Open Cluster Management project
{{- if .Values.global.deployOnOCP }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: clusterlifecycle-state-metrics-v2.rules
  namespace: {{ .Values.global.namespace }}
spec:
  groups:
    - name: acm_managed_cluster_worker_cores.rules
      rules:
        - expr: max by (hub_cluster_id, managed_cluster_id) (acm_managed_cluster_worker_cores)
          record: 'acm_managed_cluster_worker_cores:max'
{{- end }}
