# Copyright Contributors to the Open Cluster Management project
{{- if .Values.global.deployOnOCP }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}:cluster-lifecycle:clusterlifecycle-state-metrics-prometheus-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.org }}:cluster-lifecycle:clusterlifecycle-state-metrics-v2
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
{{- end }}
