# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-ocm-cluster-manager-admin: "true"
  name: multicluster-engine:discovery:admin-aggregate
rules:
- apiGroups: ["discovery.open-cluster-management.io"]
  resources: ["discoveryconfigs", "discoveredclusters"]
  verbs: ["get", "list", "watch", "update","delete", "deletecollection", "patch"]