# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: multicluster-engine:assisted-installer:edit-aggregate
rules:
- apiGroups: [ "metal3.io" ]
  resources: [ "baremetalhosts" ]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [ "agent-install.openshift.io" ]
  resources: [ "agents", "infraenvs" ]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [ "extensions.hive.openshift.io" ]
  resources: [ "agentclusterinstalls" ]
  verbs: ["get", "list", "watch", "update", "patch"]
