# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: multicluster-engine:discovery:edit-aggregate
rules:
- apiGroups: ["discovery.open-cluster-management.io"]
  resources: ["discoveryconfigs", "discoveredclusters"]
  verbs: ["get", "list", "watch", "update", "patch"]