# Copyright Contributors to the Open Cluster Management project

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: backplane-operator-catalog
  namespace: default
spec:
  displayName: Backplane Operator
  publisher: Red Hat
  sourceType: grpc
  image: "quay.io/open-cluster-management/cmb-custom-registry:v0.0.1"
  updateStrategy:
    registryPoll:
      interval: 10m
