# Copyright Contributors to the Open Cluster Management project

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:managedcluster-import-controller-v2
subjects:
- kind: ServiceAccount
  name: managedcluster-import-controller-v2
  namespace: '{{ .Values.global.namespace }}'
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Chart.Name }}:managedcluster-import-controller-v2
  apiGroup: rbac.authorization.k8s.io