apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-webhook
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      control-plane: ocm-webhook
      ocm-antiaffinity-selector: ocm-webhook
  template:
    metadata:
      labels:
        control-plane: ocm-webhook
        ocm-antiaffinity-selector: ocm-webhook
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - ocm-webhook
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - ocm-webhook
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - /webhook
        - --tls-cert-file=/var/run/ocm-webhook/tls.crt
        - --tls-private-key-file=/var/run/ocm-webhook/tls.key
        env:
{{- if .Values.hubconfig.proxyConfigs }}
        - name: HTTP_PROXY
          value: {{ .Values.hubconfig.proxyConfigs.HTTP_PROXY }}
        - name: HTTPS_PROXY
          value: {{ .Values.hubconfig.proxyConfigs.HTTPS_PROXY }}
        - name: NO_PROXY
          value: {{ .Values.hubconfig.proxyConfigs.NO_PROXY }}
{{- end }}
        image: '{{ .Values.global.imageOverrides.multicloud_manager }}'
        imagePullPolicy: '{{ .Values.global.pullPolicy }}'
        name: ocm-webhook
        ports:
        - containerPort: 8000
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: webhook-cert
            mountPath: /var/run/ocm-webhook
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ocm-foundation-sa
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - name: webhook-cert
        volumeSource:
          secret:
            defaultMode: 420
            secretName: ocm-webhook