# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Service
metadata:
  name: ocm-webhook
  labels:
    app: ocm-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ocm-webhook
spec:
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: ocm-webhook