# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:discovery-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Chart.Name }}:discovery-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
