# Copyright Contributors to the Open Cluster Management project

# Default values for console-mce-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageOverrides:
    console_mce: ""
  templateOverrides: {}
  # Available template overrides:
  # console_mce_deployment_container_memory_request: <memory-value>
  # console_mce_deployment_container_memory_limit: <memory-value>
  # console_mce_deployment_container_cpu_request: <cpu-value>
  # console_mce_deployment_container_cpu_limit: <cpu-value>
  pullPolicy: Always
  namespace: default
  pullSecret: null
  hubSize: Small
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
  ocpVersion: "4.12.0"
org: open-cluster-management
