apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assisted-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assisted-service
subjects:
- kind: ServiceAccount
  name: assisted-service
  namespace: '{{ .Values.global.namespace }}'
