- repo_name: "managed-serviceaccount"
  github_ref: "https://github.com/stolostron/managed-serviceaccount.git"
  branch: "backplane-2.8"
  charts:
    - name: "managed-serviceaccount"
      chart-path: "charts/managed-serviceaccount"
      always-or-toggle: "toggle"
      imageMappings:
        managed-serviceaccount: managed_serviceaccount
      inclusions:
        - "pullSecretOverride"
      skipRBACOverrides: true
      updateChartVersion: true # the chart version will be retrieved from trimmed branch name, e.g. backplane-2.6 -> 2.6
      escape-template-variables:
        - "CLUSTER_NAME"
        - "HUB_KUBECONFIG"
        - "INSTALL_NAMESPACE"
      auto-install-for-all-clusters: true

- repo_name: "cluster-api-installer"
  github_ref: "https://github.com/stolostron/cluster-api-installer.git"
  branch: "main"
  charts:
    - name: "cluster-api"
      chart-path: "charts/cluster-api"
      always-or-toggle: "toggle"
      imageMappings:
        ose-cluster-api-rhel9: ose_cluster_api_rhel9
      inclusions:
        - "pullSecretOverride"
      skipRBACOverrides: true
      updateChartVersion: true # the chart version will be retrieved from trimmed branch name, e.g. backplane-2.6 -> 2.6
      escape-template-variables:
        - "CLUSTER_NAME"
        - "HUB_KUBECONFIG"
        - "INSTALL_NAMESPACE"
