
- repo_name: generate-hive-bundle
  gen_command: ./hack/bundle-automation/gen-hive-bundle.sh
  branch: mce-2.2
  sha: 7f0e57561a44cbd062368d1c2a8e0f4e1825bf15
  bundlePath: /tmp/hive-operator-manifests
  name: hive-operator
  imageMappings:
     hive: openshift_hive
- repo_name: "community-operators-prod"
  github_ref: "https://github.com/redhat-openshift-ecosystem/community-operators-prod.git"
  operators:
    - name: "assisted-service"
      channel: "ocm-2.7"
      package-yml: "operators/assisted-service-operator/assisted-service.package.yaml"
      imageMappings:
        assisted-service: assisted_service
        postgresql-12-centos7: postgresql_12
        assisted-installer-agent: assisted_installer_agent
        assisted-installer-controller: assisted_installer_controller
        assisted-installer: assisted_installer
        assisted-image-service: assisted_image_service
- repo_name: registration-operator
  github_ref: "https://github.com/stolostron/registration-operator.git"
  branch: "backplane-2.2"
  operators:
    - name: cluster-manager
      bundlePath: "deploy/cluster-manager/olm-catalog/cluster-manager/manifests/"
      imageMappings:
        registration-operator: registration_operator
      exclusions:
        - readOnlyRootFilesystem
- repo_name: discovery-operator
  github_ref: "https://github.com/stolostron/discovery.git"
  branch: "backplane-2.2"
  operators:
    - name: discovery-operator
      bundlePath: "bundle/manifests/"
      imageMappings:
        discovery-operator: discovery_operator 
