- repo_name: generate-hive-bundle
  gen_command: ./hack/bundle-automation/gen-hive-bundle.sh
  branch: mce-2.5
  sha: f91ea54e9e889ed7f9ca90e415066edc328202b8
  bundlePath: /tmp/hive-operator-manifests
  name: hive-operator
  imageMappings:
    hive: openshift_hive

- repo_name: image-based-install-operator
  github_ref: "https://github.com/openshift/image-based-install-operator.git"
  branch: "main"
  operators:
    - name: image-based-install-operator
      bundlePath: "bundle/manifests/"
      imageMappings:
        controller: image_based_install_operator
      preserve_files:
        - image-based-install-config_v1_route.yaml

- repo_name: assisted-service
  github_ref: "https://github.com/openshift/assisted-service.git"
  branch: "release-ocm-2.11"
  operators:
    - name: assisted-service
      bundlePath: "deploy/olm-catalog/manifests/"
      imageMappings:
        assisted-service: assisted_service
        postgresql-12-c8s: postgresql_12
        assisted-installer-agent: assisted_installer_agent
        assisted-installer-controller: assisted_installer_controller
        assisted-installer: assisted_installer
        assisted-image-service: assisted_image_service

- repo_name: registration-operator
  github_ref: "https://github.com/stolostron/ocm.git"
  branch: "backplane-2.6"
  operators:
    - name: cluster-manager
      bundlePath: "deploy/cluster-manager/olm-catalog/cluster-manager/manifests/"
      imageMappings:
        registration-operator: registration_operator
      exclusions:
        - readOnlyRootFilesystem

- repo_name: discovery-operator
  github_ref: "https://github.com/stolostron/discovery.git"
  branch: "backplane-2.6"
  operators:
    - name: discovery-operator
      bundlePath: "bundle/manifests/"
      imageMappings:
        discovery-operator: discovery_operator
