apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Chart.Name }}:addon-manager
subjects:
  - kind: ServiceAccount
    name: cluster-proxy
    namespace: '{{ .Values.global.namespace }}'
