apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:cluster-proxy-addon:addon-manager
  namespace: '{{ .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:cluster-proxy-addon:addon-manager
subjects:
  - kind: ServiceAccount
    name: cluster-proxy
    namespace: '{{ .Values.global.namespace }}'
