apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-cluster-management:cluster-proxy-addon:addon-manager
  namespace: '{{ .Values.global.namespace }}'
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - events
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - deployments/scale
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - patch
