apiVersion: v1
kind: Service
metadata:
  name: cluster-proxy-addon-user
  labels:
    chart: cluster-proxy-addon-2.1.0
    component: cluster-proxy-addon-user
  annotations:
     service.alpha.openshift.io/serving-cert-secret-name: cluster-proxy-user-serving-cert
spec:
  ports:
  - name: user-port
    port: 9092
    protocol: TCP
  selector:
    app: cluster-proxy-addon
    component: cluster-proxy-addon-user
    release: cpa-chart

