apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-work-webhook
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    app: cluster-manager-work-webhook
  sessionAffinity: None
  type: ClusterIP

